import { PDFDocument, rgb } from 'pdf-lib'

// These coordinates must match the absolute position of the sign-here box
// in the ProposalPDF signature page (ProposalPDF.tsx — SIGN_BOX_* constants).
export const SIGN_BOX = {
  x: 40,
  yFromTop: 110,  // distance from physical page top
  width: 240,
  height: 80,
} as const

const PAGE_HEIGHT_PT = 841.89 // A4

/**
 * Injects an interactive AcroForm text field over the client "sign here" box
 * on the last page of the PDF blob generated by react-pdf.
 */
export async function addSignatureField(blob: Blob): Promise<Blob> {
  const buffer = await blob.arrayBuffer()
  const pdfDoc = await PDFDocument.load(buffer)

  const pages = pdfDoc.getPages()
  const lastPage = pages[pages.length - 1]

  const form = pdfDoc.getForm()
  const field = form.createTextField('client.signature')
  field.setFontSize(20)

  field.addToPage(lastPage, {
    x: SIGN_BOX.x,
    y: PAGE_HEIGHT_PT - SIGN_BOX.yFromTop - SIGN_BOX.height,
    width: SIGN_BOX.width,
    height: SIGN_BOX.height,
    borderColor: rgb(0.7, 0.82, 0.2),   // accent-ish border so it looks intentional
    borderWidth: 1.5,
    backgroundColor: rgb(0.98, 1, 0.94), // #fafff0 — same as highlight box
  })

  const bytes = await pdfDoc.save()
  return new Blob([bytes as BlobPart], { type: 'application/pdf' })
}
